// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace BulkyBook.Models.Models
{
    public partial class Category
    {
        public int Id { get; set; }
        [Required]
        public string Name { get; set; }
        [Range(0, 100, ErrorMessage ="Display order must be between 1 and 100")]
        public int? DisplayOrder { get; set; }
        public DateTime CreatedAt { get; set; }
    }
}